/**
 * `claude-transcripts uninstall` — remove the instance.
 *
 *   claude-transcripts uninstall [--purge] [--yes]
 *
 * Deregisters the hook, stops the stack, and removes the generated config and written
 * assets. **History survives** — it lives in bind mounts under `<deployDir>/data/`, and
 * losing it to a routine uninstall would be unforgivable, so that one directory is left
 * in place. So is the hook config: it carries the machine's own settings (mirrors, a
 * hand-set webapi URL) that the next `install` merges forward. `--purge` deletes both,
 * and only with an explicit confirmation.
 *
 * Every step tolerates already being done, so this works on a half-installed instance
 * (which is exactly when someone reaches for it).
 */
import { existsSync, readdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { parseFlags } from "../lib/args";
import { composeDown } from "../lib/compose";
import { loadOrCreateInstanceEnv } from "../lib/instance-env";
import { installPaths } from "../lib/paths";
import { runHook } from "./hook";
import { runStatusline } from "./statusline";

/** The compose stack bind-mounts its stores here (`./data/*` next to the compose file). */
const DATA_SUBDIR = "data";

/**
 * Remove the written-out deployment assets. Without `purge`, `data/` — every store's
 * bind mount — stays; the rest is regenerated by the next `install`.
 */
function removeDeployDir(deployDir: string, purge: boolean): void {
  if (purge) {
    rmSync(deployDir, { recursive: true, force: true });
    return;
  }
  let entries: string[];
  try {
    entries = readdirSync(deployDir);
  } catch {
    return; // already gone
  }
  for (const entry of entries) {
    if (entry !== DATA_SUBDIR) rmSync(join(deployDir, entry), { recursive: true, force: true });
  }
}

async function confirmPurge(auto: boolean): Promise<boolean> {
  if (auto) return true;
  process.stdout.write(
    "\nuninstall: --purge DELETES ALL RECORDED HISTORY (CouchDB + S3 data).\n" +
      "Type 'delete my history' to confirm: ",
  );
  const line = (await new Response(Bun.stdin.stream()).text()).trim();
  return line === "delete my history";
}

export async function runUninstall(argv: string[]): Promise<number> {
  const { options } = parseFlags(argv);
  const purge = options.purge === true;
  const paths = installPaths();

  if (purge && !(await confirmPurge(options.yes === true))) {
    console.error("uninstall: not confirmed — nothing was removed.");
    return 1;
  }

  console.log("uninstall: deregistering the hook and the statusline");
  await runHook(["uninstall"]);
  // `install` registers it; left behind, it would keep rendering from the kept hook
  // config. A statusLine that isn't ours is left alone (and reported) by the subcommand.
  await runStatusline(["uninstall"]);

  if (existsSync(paths.instanceEnv)) {
    console.log("uninstall: stopping the stack");
    try {
      const env = loadOrCreateInstanceEnv(paths.instanceEnv);
      await composeDown({ paths, env, app: true }, purge);
    } catch (err) {
      // A stack that's already gone (or a Docker that isn't running) must not stop us
      // cleaning up the rest.
      console.warn(`uninstall: could not stop the stack (continuing): ${(err as Error).message}`);
    }
  }

  const targets = [paths.instanceEnv, paths.versionFile, ...(purge ? [paths.hookConfig] : [])];
  for (const target of targets) {
    try {
      rmSync(target, { recursive: true, force: true });
    } catch {
      // already gone
    }
  }
  const dataDir = join(paths.deployDir, DATA_SUBDIR);
  try {
    removeDeployDir(paths.deployDir, purge);
  } catch (err) {
    // Containers can leave root-owned files in the bind mounts; say so rather than
    // report a purge that didn't happen.
    console.error(`uninstall: could not remove ${paths.deployDir}: ${(err as Error).message}`);
    if (purge) console.error(`uninstall: delete ${dataDir} by hand to finish the purge`);
    return 1;
  }
  console.log("uninstall: removed generated config and deployment assets");

  if (purge) {
    rmSync(paths.appConfig, { force: true });
    console.log("uninstall: purged history and app config");
  } else {
    console.log(`uninstall: history kept in ${dataDir}`);
    console.log(`uninstall: ${paths.hookConfig} and ${paths.appConfig} left in place`);
    console.log("uninstall: re-run with --purge to delete the data too");
  }
  console.log(`uninstall: the binary itself is still at ${paths.binDir}/claude-transcripts`);
  return 0;
}
