/**
 * The generated instance env: ports, image tags and **secrets** for one installation.
 *
 * Today the dev flow tells you to "copy `.env.template` to `.env` and fill it in
 * (IMAGE_NS, garage secrets)" — fine for a contributor, unacceptable for a user, and
 * nobody should be inventing an RPC secret by hand. Install generates this file once,
 * 0600, and it is then the single source of truth for both `docker compose` (as
 * `--env-file`) and everything the CLI does afterwards.
 *
 * Regenerating must never silently rotate a secret that a running store is already
 * using — a new CouchDB password against an existing volume locks you out. So
 * {@link loadOrCreateInstanceEnv} preserves every value that already exists and only
 * fills in what's missing.
 */
import { randomBytes } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

export type EnvMap = Record<string, string>;

/** Ports the stack binds, in the documented 7650–7661 dev range. */
export const DEFAULT_PORT_BASE = 7650;

export const PORT_KEYS = [
  "WEBAPI_PORT",
  "WEBUI_PORT",
  "COUCHDB_PORT",
  "GARAGE_S3_PORT",
  "GARAGE_ADMIN_PORT",
  "GARAGE_WEBUI_PORT",
  "MEILI_PORT",
  "MEILI_UI_PORT",
] as const;

/** URL-safe secret. Hex keeps it shell-safe and copy-pasteable in an env file. */
function secret(bytes = 32): string {
  return randomBytes(bytes).toString("hex");
}

/** Parse `KEY=value` lines, ignoring comments/blanks. Values are taken verbatim. */
export function parseEnv(text: string): EnvMap {
  const out: EnvMap = {};
  for (const line of text.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq <= 0) continue;
    out[t.slice(0, eq).trim()] = t.slice(eq + 1).trim();
  }
  return out;
}

export function formatEnv(env: EnvMap, header: string[]): string {
  const lines = header.map((h) => `# ${h}`);
  for (const [k, v] of Object.entries(env)) lines.push(`${k}=${v}`);
  return `${lines.join("\n")}\n`;
}

/**
 * Ports for an instance, laid out contiguously from `base`. One block keeps the
 * numbering predictable, which matters because these end up in printed URLs, the
 * services menu and the hook config.
 */
export function portBlock(base: number): EnvMap {
  const out: EnvMap = {};
  PORT_KEYS.forEach((key, i) => {
    out[key] = String(base + i);
  });
  return out;
}

export interface InstanceEnvOptions {
  /** First port of the block. */
  portBase?: number;
  /** Image tag for the app + registry namespace to pull it from. */
  appTag?: string;
  imageNs?: string;
  /** Turn on Meilisearch auth by generating a master key (default: keyless, ADR 0020). */
  meiliMasterKey?: boolean;
}

/**
 * Build a complete instance env. Secrets are generated; ports are laid out from the
 * base; the Garage S3 credentials are left EMPTY on purpose — they don't exist until
 * Garage is running and `provision` creates them, then writes them back here.
 */
export function buildInstanceEnv(opts: InstanceEnvOptions = {}): EnvMap {
  const base = opts.portBase ?? DEFAULT_PORT_BASE;
  const ports = portBlock(base);
  return {
    ...ports,
    WEBAPI_HOST: "127.0.0.1",
    WEBUI_HOST: "127.0.0.1",

    IMAGE_NS: opts.imageNs ?? "ghcr.io/vredchenko",
    APP_TAG: opts.appTag ?? "latest",
    COUCHDB_TAG: "3",
    GARAGE_TAG: "v2.3.0",
    GARAGE_UI_TAG: "1.1.0",
    MEILI_TAG: "v1.10",
    MEILI_UI_TAG: "latest",

    COUCHDB_URL: "",
    COUCHDB_HOST: "127.0.0.1",
    COUCHDB_USER: "admin",
    // CouchDB 3 refuses to start without an admin, so this is required, not optional.
    COUCHDB_PASSWORD: secret(16),

    S3_ENDPOINT: `http://127.0.0.1:${ports.GARAGE_S3_PORT}`,
    S3_REGION: "garage",
    // Created by `provision` once Garage is up — see the doc comment above.
    S3_ACCESS_KEY: "",
    S3_SECRET_KEY: "",

    GARAGE_RPC_SECRET: secret(32),
    GARAGE_ADMIN_TOKEN: secret(32),
    GARAGE_METRICS_TOKEN: secret(32),

    MEILI_HOST: `http://127.0.0.1:${ports.MEILI_PORT}`,
    // Keyless by default (ADR 0020: bundled services, localhost, no auth). Set this
    // and the whole path — compose, webapi, CLI — picks the key up.
    MEILI_MASTER_KEY: opts.meiliMasterKey ? secret(24) : "",
    MEILI_API_KEY: "",
  };
}

const HEADER = [
  "Generated by `claude-transcripts install` — do not edit while the stack is running.",
  "Holds this instance's ports and secrets. Never commit it.",
  "Rotating a secret here does NOT rotate it in an already-provisioned store.",
];

/**
 * Load the instance env, creating it if absent and back-filling any missing keys.
 *
 * Back-filling rather than regenerating is the important part: an upgrade that adds a
 * new key must not rotate the CouchDB password an existing volume authenticates
 * against.
 */
export function loadOrCreateInstanceEnv(path: string, opts: InstanceEnvOptions = {}): EnvMap {
  const generated = buildInstanceEnv(opts);
  const existing = existsSync(path) ? parseEnv(readFileSync(path, "utf8")) : {};
  const merged: EnvMap = { ...generated, ...existing };

  // A key present but empty is "not yet provisioned" (the S3 pair), not "keep empty" —
  // except where empty is a real choice, which is only the Meili key.
  for (const [k, v] of Object.entries(generated)) {
    if (merged[k] === undefined) merged[k] = v;
  }

  writeInstanceEnv(path, merged);
  return merged;
}

export function writeInstanceEnv(path: string, env: EnvMap): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, formatEnv(env, HEADER));
  chmodSync(path, 0o600);
}

/** Update specific keys in place, preserving everything else. */
export function updateInstanceEnv(path: string, patch: EnvMap): EnvMap {
  const env = existsSync(path) ? parseEnv(readFileSync(path, "utf8")) : {};
  const next = { ...env, ...patch };
  writeInstanceEnv(path, next);
  return next;
}
