/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Claude Transcripts
 * OpenAPI spec version: 0.0.0-dev
 */
import { customFetch } from "./http";
export type SessionStatus = (typeof SessionStatus)[keyof typeof SessionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SessionStatus = {
  ended: "ended",
  running: "running",
  incomplete: "incomplete",
} as const;

export interface TokenUsage {
  input: number;
  output: number;
  cacheCreation: number;
  cacheRead: number;
  total: number;
  messages: number;
}

export type SessionSummaryToolCounts = { [key: string]: number };

export interface SessionSummary {
  sessionId: string;
  timestamp: string;
  startTimestamp?: string;
  durationMs?: number;
  activeMs?: number;
  model?: string;
  cwd: string;
  hostname: string;
  eventCount: number;
  promptCount: number;
  errorCount: number;
  toolCounts: SessionSummaryToolCounts;
  endReason: string;
  hasTranscript: boolean;
  transcriptSize?: number;
  status: SessionStatus;
  lastActivity?: string;
  tokenUsage?: TokenUsage;
  source?: string;
}

export interface SessionsResponse {
  sessions: SessionSummary[];
  totalCount: number;
}

export interface ApiError {
  error: string;
}

export type SpeakerRole = (typeof SpeakerRole)[keyof typeof SpeakerRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SpeakerRole = {
  user: "user",
  assistant: "assistant",
  tool_result: "tool_result",
  system: "system",
  other: "other",
} as const;

export interface ToolUseRef {
  name: string;
  id?: string;
}

export interface TranscriptEntry {
  role: SpeakerRole;
  timestamp?: string;
  text?: string;
  /** @nullable */
  toolUses?: ToolUseRef[] | null;
  /** @nullable */
  toolUseId?: string | null;
  isError?: boolean;
  isSidechain?: boolean;
}

export type TranscriptSource = (typeof TranscriptSource)[keyof typeof TranscriptSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TranscriptSource = {
  chunks: "chunks",
  s3: "s3",
} as const;

export interface TranscriptResponse {
  entries: TranscriptEntry[];
  totalCount: number;
  hasMore: boolean;
  source: TranscriptSource;
  byteCoverage: number;
}

export interface SpeakerTurn {
  role: SpeakerRole;
  timestamp: string;
  text: string;
  /** @nullable */
  toolUses?: ToolUseRef[] | null;
  /** @nullable */
  toolUseId?: string | null;
  isError?: boolean;
}

/**
 * @nullable
 */
export type SessionTurnsResponseRoleAllOf = unknown | null;

export type SessionTurnsResponseRole = SpeakerRole & SessionTurnsResponseRoleAllOf;

export interface SessionTurnsResponse {
  turns: SpeakerTurn[];
  totalCount: number;
  hasMore: boolean;
  role: SessionTurnsResponseRole;
}

export interface CrossSessionTurn {
  sessionId: string;
  cwd: string;
  role: SpeakerRole;
  timestamp: string;
  text: string;
}

/**
 * @nullable
 */
export type CrossSessionTurnsResponseRoleAllOf = unknown | null;

export type CrossSessionTurnsResponseRole = SpeakerRole & CrossSessionTurnsResponseRoleAllOf;

export interface CrossSessionTurnsResponse {
  turns: CrossSessionTurn[];
  hasMore: boolean;
  role: CrossSessionTurnsResponseRole;
}

export type SessionResetResultDeleted = {
  summary: number;
  events: number;
  chunks: number;
};

export interface SessionResetResult {
  ok: boolean;
  id: string;
  deleted: SessionResetResultDeleted;
}

export interface SearchHit {
  sessionId: string;
  timestamp?: string;
  cwd?: string;
  model?: string;
  hostname?: string;
  endReason?: string;
  source?: string;
  tools?: string[];
}

export interface TurnHit {
  sessionId: string;
  role: string;
  snippet: string;
  timestamp?: string;
  cwd?: string;
}

export interface SearchResponse {
  hits: SearchHit[];
  turns: TurnHit[];
  query: string;
  enabled: boolean;
}

export interface IndexCounts {
  scanned: number;
  indexed: number;
}

export interface ReindexResult {
  enabled: boolean;
  sessions: IndexCounts;
  turns: IndexCounts;
  failures: string[];
}

export interface MigrationStep {
  id: number;
  name: string;
}

export interface AppliedMigration {
  id: number;
  name: string;
  at: string;
}

export interface MigrationStatus {
  currentVersion: number;
  latestVersion: number;
  pending: MigrationStep[];
  history: AppliedMigration[];
}

export type MigrationDirection = (typeof MigrationDirection)[keyof typeof MigrationDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MigrationDirection = {
  up: "up",
  down: "down",
} as const;

export interface MigrationRunResult {
  direction: MigrationDirection;
  fromVersion: number;
  toVersion: number;
  applied: MigrationStep[];
  dryRun: boolean;
  log: string[];
}

export type ListSessionsParams = {
  /**
   * @minimum 0
   * @nullable
   */
  limit?: number | null;
  /**
   * @minimum 0
   * @nullable
   */
  skip?: number | null;
};

export type GetSessionTranscriptParams = {
  /**
   * @minimum 0
   * @nullable
   */
  limit?: number | null;
  /**
   * @minimum 0
   * @nullable
   */
  offset?: number | null;
};

export type GetSessionTurnsParams = {
  role?: SpeakerRole;
  /**
   * @minimum 0
   * @nullable
   */
  limit?: number | null;
  /**
   * @minimum 0
   * @nullable
   */
  offset?: number | null;
};

export type GetTurnsParams = {
  role?: SpeakerRole;
  from?: string;
  to?: string;
  /**
   * @minimum 0
   * @nullable
   */
  limit?: number | null;
  /**
   * @minimum 0
   * @nullable
   */
  skip?: number | null;
};

export type IngestSummaryBodyType =
  (typeof IngestSummaryBodyType)[keyof typeof IngestSummaryBodyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IngestSummaryBodyType = {
  summary: "summary",
} as const;

export type IngestSummaryBodyEvent =
  (typeof IngestSummaryBodyEvent)[keyof typeof IngestSummaryBodyEvent];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IngestSummaryBodyEvent = {
  SessionEnd: "SessionEnd",
} as const;

export type IngestSummaryBodyToolCounts = { [key: string]: number };

export type IngestSummaryBodyTokenUsage = {
  input: number;
  output: number;
  cacheCreation: number;
  cacheRead: number;
  total: number;
  messages: number;
};

export type IngestSummaryBody = {
  _id: string;
  type: IngestSummaryBodyType;
  event: IngestSummaryBodyEvent;
  session_id: string;
  timestamp: string;
  hostname: string;
  cwd: string;
  model?: string;
  end_reason: string;
  event_count: number;
  prompt_count: number;
  error_count: number;
  tool_counts: IngestSummaryBodyToolCounts;
  transcript_bytes: number;
  token_usage: IngestSummaryBodyTokenUsage;
  source?: string;
  backfilled_at?: string;
  actor?: string;
};

export type IngestSummary200 = {
  ok: boolean;
  id?: string;
  updated?: boolean;
  inserted?: number;
  bytes?: number;
};

export type IngestSummary400 = {
  error: string;
};

export type IngestSummary500 = {
  error: string;
};

export type IngestEventsBodyDocsItemType =
  (typeof IngestEventsBodyDocsItemType)[keyof typeof IngestEventsBodyDocsItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IngestEventsBodyDocsItemType = {
  event: "event",
} as const;

export type IngestEventsBodyDocsItem = {
  type: IngestEventsBodyDocsItemType;
  event: string;
  session_id: string;
  timestamp: string;
  hostname: string;
  cwd: string;
};

export type IngestEventsBody = {
  docs: IngestEventsBodyDocsItem[];
};

export type IngestEvents200 = {
  ok: boolean;
  id?: string;
  updated?: boolean;
  inserted?: number;
  bytes?: number;
};

export type IngestEvents400 = {
  error: string;
};

export type IngestEvents500 = {
  error: string;
};

export type IngestChunksBodyDocsItemType =
  (typeof IngestChunksBodyDocsItemType)[keyof typeof IngestChunksBodyDocsItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IngestChunksBodyDocsItemType = {
  chunk: "chunk",
} as const;

export type IngestChunksBodyDocsItemEntriesItemRole =
  (typeof IngestChunksBodyDocsItemEntriesItemRole)[keyof typeof IngestChunksBodyDocsItemEntriesItemRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IngestChunksBodyDocsItemEntriesItemRole = {
  user: "user",
  assistant: "assistant",
  tool_result: "tool_result",
  system: "system",
  other: "other",
} as const;

export type IngestChunksBodyDocsItemEntriesItemToolUsesItem = {
  name: string;
  id?: string;
};

export type IngestChunksBodyDocsItemEntriesItem = {
  role: IngestChunksBodyDocsItemEntriesItemRole;
  timestamp?: string;
  text?: string;
  toolUses?: IngestChunksBodyDocsItemEntriesItemToolUsesItem[];
  toolUseId?: string;
  isError?: boolean;
  isSidechain?: boolean;
};

export type IngestChunksBodyDocsItem = {
  _id: string;
  type: IngestChunksBodyDocsItemType;
  session_id: string;
  byte_start: number;
  byte_end: number;
  entry_count: number;
  timestamp: string;
  hostname: string;
  cwd: string;
  schema_version: number;
  entries?: IngestChunksBodyDocsItemEntriesItem[];
};

export type IngestChunksBody = {
  docs: IngestChunksBodyDocsItem[];
};

export type IngestChunks200 = {
  ok: boolean;
  id?: string;
  updated?: boolean;
  inserted?: number;
  bytes?: number;
};

export type IngestChunks400 = {
  error: string;
};

export type IngestChunks500 = {
  error: string;
};

export type IngestTranscript200 = {
  ok: boolean;
  id?: string;
  updated?: boolean;
  inserted?: number;
  bytes?: number;
};

export type IngestTranscript400 = {
  error: string;
};

export type IngestTranscript500 = {
  error: string;
};

export type ResetSession400 = {
  error: string;
};

export type ResetSession500 = {
  error: string;
};

export type SearchParams = {
  q?: string;
  /**
   * @minimum 0
   * @nullable
   */
  limit?: number | null;
};

export type MigrateUpBody = {
  to?: number;
  dryRun?: boolean;
};

export type MigrateDownBody = {
  steps?: number;
  dryRun?: boolean;
};

export const getListSessionsUrl = (params?: ListSessionsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sessions?${stringifiedParams}` : `/api/sessions`;
};

export const listSessions = async (
  params?: ListSessionsParams,
  options?: RequestInit,
): Promise<SessionsResponse> => {
  return customFetch<SessionsResponse>(getListSessionsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetSessionUrl = (id: string) => {
  return `/api/sessions/${id}`;
};

export const getSession = async (id: string, options?: RequestInit): Promise<SessionSummary> => {
  return customFetch<SessionSummary>(getGetSessionUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetSessionTranscriptUrl = (id: string, params?: GetSessionTranscriptParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/sessions/${id}/transcript?${stringifiedParams}`
    : `/api/sessions/${id}/transcript`;
};

export const getSessionTranscript = async (
  id: string,
  params?: GetSessionTranscriptParams,
  options?: RequestInit,
): Promise<TranscriptResponse> => {
  return customFetch<TranscriptResponse>(getGetSessionTranscriptUrl(id, params), {
    ...options,
    method: "GET",
  });
};

export const getGetSessionTurnsUrl = (id: string, params?: GetSessionTurnsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/sessions/${id}/turns?${stringifiedParams}`
    : `/api/sessions/${id}/turns`;
};

export const getSessionTurns = async (
  id: string,
  params?: GetSessionTurnsParams,
  options?: RequestInit,
): Promise<SessionTurnsResponse> => {
  return customFetch<SessionTurnsResponse>(getGetSessionTurnsUrl(id, params), {
    ...options,
    method: "GET",
  });
};

export const getGetTurnsUrl = (params?: GetTurnsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/turns?${stringifiedParams}` : `/api/turns`;
};

export const getTurns = async (
  params?: GetTurnsParams,
  options?: RequestInit,
): Promise<CrossSessionTurnsResponse> => {
  return customFetch<CrossSessionTurnsResponse>(getGetTurnsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getIngestSummaryUrl = () => {
  return `/api/ingest/summary`;
};

export const ingestSummary = async (
  ingestSummaryBody: IngestSummaryBody,
  options?: RequestInit,
): Promise<IngestSummary200> => {
  return customFetch<IngestSummary200>(getIngestSummaryUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(ingestSummaryBody),
  });
};

export const getIngestEventsUrl = () => {
  return `/api/ingest/events`;
};

export const ingestEvents = async (
  ingestEventsBody: IngestEventsBody,
  options?: RequestInit,
): Promise<IngestEvents200> => {
  return customFetch<IngestEvents200>(getIngestEventsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(ingestEventsBody),
  });
};

export const getIngestChunksUrl = () => {
  return `/api/ingest/chunks`;
};

export const ingestChunks = async (
  ingestChunksBody: IngestChunksBody,
  options?: RequestInit,
): Promise<IngestChunks200> => {
  return customFetch<IngestChunks200>(getIngestChunksUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(ingestChunksBody),
  });
};

/**
 * @summary Store a session transcript (raw JSONL body, application/x-ndjson) in S3
 */
export const getIngestTranscriptUrl = (id: string) => {
  return `/api/ingest/${id}/transcript`;
};

export const ingestTranscript = async (
  id: string,
  options?: RequestInit,
): Promise<IngestTranscript200> => {
  return customFetch<IngestTranscript200>(getIngestTranscriptUrl(id), {
    ...options,
    method: "PUT",
  });
};

/**
 * @summary Delete a session's summary/event/chunk docs so it can be re-ingested
 */
export const getResetSessionUrl = (id: string) => {
  return `/api/ingest/${id}`;
};

export const resetSession = async (
  id: string,
  options?: RequestInit,
): Promise<SessionResetResult> => {
  return customFetch<SessionResetResult>(getResetSessionUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getSearchUrl = (params?: SearchParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/search?${stringifiedParams}` : `/api/search`;
};

export const search = async (
  params?: SearchParams,
  options?: RequestInit,
): Promise<SearchResponse> => {
  return customFetch<SearchResponse>(getSearchUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getSearchReindexUrl = () => {
  return `/api/search/reindex`;
};

export const searchReindex = async (options?: RequestInit): Promise<ReindexResult> => {
  return customFetch<ReindexResult>(getSearchReindexUrl(), {
    ...options,
    method: "POST",
  });
};

export const getMigrateStatusUrl = () => {
  return `/api/migrate/status`;
};

export const migrateStatus = async (options?: RequestInit): Promise<MigrationStatus> => {
  return customFetch<MigrationStatus>(getMigrateStatusUrl(), {
    ...options,
    method: "GET",
  });
};

export const getMigrateUpUrl = () => {
  return `/api/migrate/up`;
};

export const migrateUp = async (
  migrateUpBody?: MigrateUpBody,
  options?: RequestInit,
): Promise<MigrationRunResult> => {
  return customFetch<MigrationRunResult>(getMigrateUpUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(migrateUpBody),
  });
};

export const getMigrateDownUrl = () => {
  return `/api/migrate/down`;
};

export const migrateDown = async (
  migrateDownBody?: MigrateDownBody,
  options?: RequestInit,
): Promise<MigrationRunResult> => {
  return customFetch<MigrationRunResult>(getMigrateDownUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(migrateDownBody),
  });
};
