#!/usr/bin/env bun
/**
 * Inline the deployment assets into the CLI as a generated module.
 *
 *   bun run scripts/gen-assets.ts   (or: bun run gen:assets)
 *
 * A user install has no repo, so the compose files and config template have to travel
 * *inside* the binary and be written out at install time (installation.md). Embedding
 * them as strings works identically under `bun run` and `bun build --compile`, and
 * removes any chance of the assets drifting from the code that drives them — they ship
 * as one artifact.
 *
 * Dev-only tooling; the output is committed like the other generated files.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const OUT = join(ROOT, "packages", "cli", "src", "lib", "assets.generated.ts");

/** Files written into the instance's data dir at install time. */
const ASSETS: { key: string; from: string; to: string }[] = [
  { key: "compose", from: "deploy/docker-compose.yml", to: "deploy/docker-compose.yml" },
  {
    key: "composeUpstream",
    from: "deploy/docker-compose.upstream.yml",
    to: "deploy/docker-compose.upstream.yml",
  },
  { key: "appConfig", from: "config/config.template.json", to: "config/app.json" },
];

const entries = ASSETS.map(({ key, from, to }) => {
  const content = readFileSync(join(ROOT, from), "utf8");
  return `  ${key}: {\n    path: ${JSON.stringify(to)},\n    source: ${JSON.stringify(from)},\n    content: ${JSON.stringify(content)},\n  },`;
}).join("\n");

const banner = `/**
 * GENERATED by scripts/gen-assets.ts (bun run gen:assets) — do not edit by hand.
 *
 * The deployment assets, inlined so an installed binary can write them out without a
 * repo or a second download. Regenerate after changing anything under deploy/ or
 * config/config.template.json.
 */

export interface EmbeddedAsset {
  /** Destination, relative to the instance data dir. */
  path: string;
  /** Where it came from in the repo (provenance, for error messages). */
  source: string;
  content: string;
}

export const EMBEDDED_ASSETS = {
${entries}
} as const satisfies Record<string, EmbeddedAsset>;

export type EmbeddedAssetKey = keyof typeof EMBEDDED_ASSETS;
`;

writeFileSync(OUT, banner);
console.log(`[assets] embedded ${ASSETS.length} file(s) → ${OUT}`);
