#!/usr/bin/env bun
import { mkdir, readdir, rm } from "node:fs/promises";
import { join } from "node:path";
/**
 * Generate deploy/k8s/base/ — a kustomize base — from the app model (services
 * topology). The Kubernetes manifests are a PROJECTION (toKubernetesObjects), the
 * sibling of deploy/docker-compose.yml: generated, not hand-maintained. Re-run after
 * changing the model's SERVICES.
 *
 *   bun run scripts/gen-k8s.ts   (or: bun run gen:k8s)
 *
 * Also writes deploy/k8s/base/.env.template — the variables the generated Secret
 * must carry, projected from the same `${VAR}` references compose reads from .env.
 */
import {
  buildAppModel,
  k8sSecretKeys,
  toKubernetesObjects,
  toKustomization,
} from "@claude-transcripts/shared";
import { stringify } from "yaml";
import { loadConfigFile } from "./lib/config-file";

const ROOT = join(import.meta.dir, "..");
const OUT = join(ROOT, "deploy", "k8s", "base");
const model = buildAppModel(loadConfigFile(ROOT), process.env);

// Read-only file mounts come from the same files compose mounts (deploy/garage.toml),
// inlined into ConfigMaps — kustomize refuses to read files above its own directory,
// and a copy would be a second thing to keep in step.
const files = { "./garage.toml": await Bun.file(join(ROOT, "deploy", "garage.toml")).text() };

const header = (
  script: string,
) => `# GENERATED from the app model (@claude-transcripts/shared) by scripts/gen-k8s.ts.
# Do NOT edit by hand — run \`bun run gen:k8s\` to regenerate, and change the model
# (packages/shared/src/model/services.ts) instead. Inline edits here are lost silently.
# Overrides belong in a kustomize overlay — see deploy/k8s/README.md.
${script}
`;

const objects = toKubernetesObjects(model, { files });

// One file per service (by the app.kubernetes.io/name label); namespace first.
// No anchors/aliases (`&a1`/`*a1` for the repeated label maps — valid, unreadable) and
// no line folding (it turns the inlined garage.toml into a folded scalar).
const yaml = (o: unknown) => stringify(o, { aliasDuplicateObjects: false, lineWidth: 0 });
const byFile = new Map<string, string[]>();
for (const o of objects) {
  const file =
    o.kind === "Namespace"
      ? "namespace.yaml"
      : `${o.metadata.labels?.["app.kubernetes.io/name"]}.yaml`;
  const docs = byFile.get(file) ?? [];
  docs.push(yaml(o));
  byFile.set(file, docs);
}

// Remove only what we generate — never the whole directory: the operator's `.env`
// (the secretGenerator input) lives here too, and a regen must not wipe it.
await mkdir(OUT, { recursive: true });
for (const f of await readdir(OUT)) {
  if (f.endsWith(".yaml") || f === ".env.template") await rm(join(OUT, f));
}
for (const [file, docs] of byFile) {
  await Bun.write(join(OUT, file), header("") + docs.join("---\n"));
}
await Bun.write(
  join(OUT, "kustomization.yaml"),
  header(`#
# Apply with:  kubectl apply -k deploy/k8s/base     (after: cp .env.template .env; edit)
# The Secret is built from ./.env by the secretGenerator below; .env is gitignored.`) +
    yaml(toKustomization([...byFile.keys()])),
);

const template = [
  "# GENERATED by scripts/gen-k8s.ts — the variables the claude-transcripts-env Secret",
  "# carries (kustomize secretGenerator, envs: [.env]). Copy to .env and fill in; the",
  "# names are the ones the compose stack reads from the repo-root .env, so that file",
  "# is a valid starting point too. Never commit .env.",
  "#",
  "# Empty = required, no default (Garage cluster secrets: openssl rand -hex 32; the",
  "# app's S3_ACCESS_KEY / S3_SECRET_KEY come from the one-time Garage bootstrap).",
  "# The stack runs with NO app-level auth (ADR 0020): keep it ClusterIP / tailnet-only.",
  "",
  ...k8sSecretKeys(model).map(({ name, fallback }) => `${name}=${fallback ?? ""}`),
  "",
].join("\n");
await Bun.write(join(OUT, ".env.template"), template);

console.log(
  `[gen-k8s] wrote deploy/k8s/base/ (${byFile.size} manifests + kustomization + .env.template)`,
);
