/**
 * Runtime config for the hook. Generated by the setup step (the CLI / scripts):
 * non-secret settings baked from `config/`, secrets from `.env`.
 * Stores are keyed maps (multi-database / multi-bucket).
 */
import { readFileSync } from "node:fs";

export interface HookConfig {
  couch: { url: string; databases: Record<string, string>; auth?: string };
  blob?: {
    endpoint: string;
    region: string;
    accessKey?: string;
    secretKey?: string;
    buckets: Record<string, string>;
  };
  features: Record<string, boolean>;
  system: { logging: { chunk: { maxEntriesPerChunk: number; flushIntervalMs: number } } };
}

export function loadConfig(): HookConfig | null {
  const path =
    process.env.CT_HOOK_CONFIG ?? `${process.env.HOME}/.config/claude-transcripts/config.json`;
  try {
    return JSON.parse(readFileSync(path, "utf8")) as HookConfig;
  } catch {
    return null; // no config → the hook silently does nothing
  }
}
