import { describe, expect, it } from "bun:test";
import type { TranscriptEntry } from "./api/generated";
import {
  buildTimeline,
  countTurns,
  type HiddenNode,
  hiddenCount,
  isDialogue,
  isSyntheticUserText,
  nodeIndexContaining,
  stripSystemReminders,
  summarizeHidden,
  type TurnNode,
} from "./transcript-timeline";

const entry = (e: Partial<TranscriptEntry>): TranscriptEntry =>
  ({ role: "other", ...e }) as TranscriptEntry;

const user = (text: string, extra: Partial<TranscriptEntry> = {}) =>
  entry({ role: "user", text, ...extra });
const assistant = (text: string, extra: Partial<TranscriptEntry> = {}) =>
  entry({ role: "assistant", text, ...extra });
const toolResult = (text: string, extra: Partial<TranscriptEntry> = {}) =>
  entry({ role: "tool_result", text, ...extra });

const turns = (nodes: ReturnType<typeof buildTimeline>): TurnNode[] =>
  nodes.filter((n): n is TurnNode => n.type === "turn");
const hidden = (nodes: ReturnType<typeof buildTimeline>): HiddenNode[] =>
  nodes.filter((n): n is HiddenNode => n.type === "hidden");

describe("stripSystemReminders", () => {
  it("removes injected reminder blocks and trims what is left", () => {
    expect(stripSystemReminders("before <system-reminder>noise</system-reminder> after")).toBe(
      "before  after",
    );
    expect(stripSystemReminders("<system-reminder>only noise</system-reminder>")).toBe("");
  });

  it("removes every block, including multi-line ones", () => {
    const text = "<system-reminder>a\nb</system-reminder>ask<system-reminder>c</system-reminder>";
    expect(stripSystemReminders(text)).toBe("ask");
  });

  it("leaves ordinary text alone", () => {
    expect(stripSystemReminders("fix the parser")).toBe("fix the parser");
  });
});

describe("isSyntheticUserText", () => {
  it("flags slash-command echoes and hook output", () => {
    expect(isSyntheticUserText("<command-name>/clear</command-name>")).toBe(true);
    expect(isSyntheticUserText("<local-command-stdout>ok</local-command-stdout>")).toBe(true);
    expect(isSyntheticUserText("<user-prompt-submit-hook>ran</user-prompt-submit-hook>")).toBe(
      true,
    );
  });

  it("flags the local-command caveat preamble", () => {
    expect(
      isSyntheticUserText(
        "Caveat: The messages below were generated by the user while running local commands.",
      ),
    ).toBe(true);
  });

  it("flags a turn that is nothing but a system reminder", () => {
    expect(isSyntheticUserText("<system-reminder>context</system-reminder>")).toBe(true);
  });

  it("passes a real prompt through, reminder attached or not", () => {
    expect(isSyntheticUserText("please rename the module")).toBe(false);
    expect(isSyntheticUserText("please rename it<system-reminder>context</system-reminder>")).toBe(
      false,
    );
  });
});

describe("isDialogue", () => {
  it("accepts prompts and assistant prose", () => {
    expect(isDialogue(user("do the thing"))).toBe(true);
    expect(isDialogue(assistant("done"))).toBe(true);
  });

  it("rejects an assistant turn that is only tool calls", () => {
    expect(isDialogue(entry({ role: "assistant", toolUses: [{ name: "Read" }] }))).toBe(false);
  });

  it("keeps an assistant turn that has both prose and tool calls", () => {
    expect(isDialogue(assistant("looking now", { toolUses: [{ name: "Read" }] }))).toBe(true);
  });

  it("rejects tool results, system lines and kind-bearing entries", () => {
    expect(isDialogue(toolResult("file contents"))).toBe(false);
    expect(
      isDialogue(entry({ role: "system", text: "turn took 3s", kind: "system:turn_duration" })),
    ).toBe(false);
    expect(
      isDialogue(entry({ role: "other", text: "hook ok", kind: "attachment:hook_success" })),
    ).toBe(false);
  });

  it("keeps a subagent's dialogue — it is still someone talking", () => {
    expect(isDialogue(assistant("sub-answer", { isSidechain: true }))).toBe(true);
  });
});

describe("buildTimeline", () => {
  const entries = [
    user("add a timeline"),
    assistant("on it", { toolUses: [{ name: "Read" }, { name: "Read" }] }),
    entry({ role: "assistant", toolUses: [{ name: "Bash" }] }),
    toolResult("ok"),
    toolResult("boom", { isError: true }),
    entry({ role: "other", text: "hook ok", kind: "attachment:hook_success" }),
    assistant("here you go"),
  ];

  it("keeps only dialogue as turns, in order", () => {
    const nodes = buildTimeline(entries);
    expect(turns(nodes).map((t) => [t.speaker, t.text])).toEqual([
      ["user", "add a timeline"],
      ["assistant", "on it"],
      ["assistant", "here you go"],
    ]);
  });

  it("collapses each run of non-dialogue into one node", () => {
    const runs = hidden(buildTimeline(entries));
    expect(runs).toHaveLength(1);
    expect(hiddenCount(runs[0] as HiddenNode)).toBe(4);
    expect(runs[0]?.index).toBe(2);
  });

  it("loses nothing: every entry lands in exactly one node, in order", () => {
    const nodes = buildTimeline(entries);
    const indices = nodes.flatMap((n) =>
      n.type === "turn" ? [n.index] : n.entries.map((e) => e.index),
    );
    expect(indices).toEqual(entries.map((_e, i) => i));
  });

  it("tallies the tools and errors inside a collapsed run", () => {
    const run = hidden(buildTimeline(entries))[0] as HiddenNode;
    expect(run.tools).toEqual([{ name: "Bash", count: 1 }]);
    expect(run.errorCount).toBe(1);
    expect(run.kinds).toEqual([
      { name: "tool_result", count: 2 },
      { name: "assistant", count: 1 },
      { name: "attachment:hook_success", count: 1 },
    ]);
  });

  it("tallies a turn's own tool calls by name", () => {
    expect(turns(buildTimeline(entries))[1]?.tools).toEqual([{ name: "Read", count: 2 }]);
  });

  it("indexes turns by their position in the transcript, not in the timeline", () => {
    expect(turns(buildTimeline(entries)).map((t) => t.index)).toEqual([0, 1, 6]);
  });

  it("handles a transcript with no dialogue at all", () => {
    const nodes = buildTimeline([toolResult("a"), toolResult("b")]);
    expect(countTurns(nodes)).toBe(0);
    expect(hiddenCount(nodes[0] as HiddenNode)).toBe(2);
  });

  it("handles an empty transcript", () => {
    expect(buildTimeline([])).toEqual([]);
  });

  it("strips reminder blocks from the text it displays", () => {
    const nodes = buildTimeline([user("ship it<system-reminder>context</system-reminder>")]);
    expect(turns(nodes)[0]?.text).toBe("ship it");
  });

  it("folds a synthetic user turn away instead of showing it as a prompt", () => {
    const nodes = buildTimeline([user("<command-name>/clear</command-name>"), user("hello")]);
    expect(turns(nodes).map((t) => t.text)).toEqual(["hello"]);
    expect(hiddenCount(hidden(nodes)[0] as HiddenNode)).toBe(1);
  });
});

describe("buildTimeline elapsed time", () => {
  const at = (iso: string, text: string) => user(text, { timestamp: iso });

  it("measures from the previous turn, skipping what was collapsed", () => {
    const nodes = buildTimeline([
      at("2026-03-18T10:00:00Z", "one"),
      toolResult("noise", { timestamp: "2026-03-18T10:01:00Z" }),
      at("2026-03-18T10:05:00Z", "two"),
    ]);
    expect(turns(nodes).map((t) => t.sincePrevMs)).toEqual([undefined, 300_000]);
  });

  it("omits the gap when a timestamp is missing", () => {
    const nodes = buildTimeline([user("one"), at("2026-03-18T10:05:00Z", "two")]);
    expect(turns(nodes)[1]?.sincePrevMs).toBeUndefined();
  });

  it("omits a backwards gap rather than rendering negative time", () => {
    const nodes = buildTimeline([
      at("2026-03-18T10:05:00Z", "one"),
      at("2026-03-18T10:00:00Z", "two"),
    ]);
    expect(turns(nodes)[1]?.sincePrevMs).toBeUndefined();
  });

  it("carries the last known timestamp forward past an undated turn", () => {
    const nodes = buildTimeline([
      at("2026-03-18T10:00:00Z", "one"),
      user("two"),
      at("2026-03-18T10:02:00Z", "three"),
    ]);
    expect(turns(nodes)[2]?.sincePrevMs).toBe(120_000);
  });
});

describe("summarizeHidden", () => {
  const run = (entries: TranscriptEntry[]): HiddenNode =>
    hidden(buildTimeline(entries))[0] as HiddenNode;

  it("leads with the tools that ran", () => {
    const node = run([
      entry({
        role: "assistant",
        toolUses: [{ name: "Read" }, { name: "Read" }, { name: "Bash" }],
      }),
      toolResult("x"),
    ]);
    expect(summarizeHidden(node)).toBe("Read ×2, Bash");
  });

  it("caps the tool list and says how many it dropped", () => {
    const node = run([
      entry({
        role: "assistant",
        toolUses: [{ name: "A" }, { name: "B" }, { name: "C" }, { name: "D" }],
      }),
    ]);
    expect(summarizeHidden(node)).toBe("A, B, C, +1");
  });

  it("names the other kinds, without repeating what the tool list already said", () => {
    const node = run([
      entry({ role: "assistant", toolUses: [{ name: "Read" }] }),
      toolResult("x"),
      entry({ role: "other", text: "hook", kind: "attachment:hook_success" }),
    ]);
    expect(summarizeHidden(node)).toBe("Read · attachment:hook_success");
  });

  it("describes a run with no tools by its kinds alone", () => {
    expect(summarizeHidden(run([entry({ role: "system", kind: "system:turn_duration" })]))).toBe(
      "system:turn_duration",
    );
  });

  it("names tool results when there is no tool list to imply them", () => {
    // The calls can sit on an earlier page, or in a turn the reader already scrolled
    // past. Filtering the kind unconditionally left such a run labelled with nothing.
    expect(summarizeHidden(run([toolResult("a"), toolResult("b")]))).toBe("tool_result ×2");
  });
});

describe("nodeIndexContaining", () => {
  const nodes = buildTimeline([user("one"), toolResult("a"), toolResult("b"), assistant("two")]);

  it("finds the turn holding an entry", () => {
    expect(nodeIndexContaining(nodes, 0)).toBe(0);
    expect(nodeIndexContaining(nodes, 3)).toBe(2);
  });

  it("finds the collapsed run holding an entry", () => {
    expect(nodeIndexContaining(nodes, 1)).toBe(1);
    expect(nodeIndexContaining(nodes, 2)).toBe(1);
  });

  it("returns -1 for no match", () => {
    expect(nodeIndexContaining(nodes, -1)).toBe(-1);
    expect(nodeIndexContaining(nodes, 99)).toBe(-1);
  });
});
