/**
 * Fold a flat transcript into a conversation timeline.
 *
 * A stored transcript is not a conversation. In a real corpus the dialogue — the
 * prompts a person typed and the prose Claude wrote back — is a minority of the lines:
 * the rest is tool calls, tool results, attachments, file-history snapshots, mode
 * changes and system notices. Rendered one row per line, the conversation is there but
 * unreadable, and scrolling it is mostly scrolling past machinery.
 *
 * So this splits the entries in two. Dialogue turns become timeline nodes carrying the
 * text. Every run of consecutive non-dialogue lines collapses into a single `hidden`
 * node that says what happened in it (which tools ran, how many lines, whether any
 * errored) and keeps the entries so the reader can open it. Nothing is dropped —
 * `buildTimeline` is a lossless partition, which is what the tests pin.
 *
 * Pure and out of the component for the usual reason: the classification is where the
 * judgement calls live, and they are far easier to argue with as assertions.
 */
import type { TranscriptEntry } from "./api/generated";

/** Who is speaking in a dialogue turn. */
export type Speaker = "user" | "assistant";

/** A name with a count — a tool tally or a kind tally. */
export interface Tally {
  name: string;
  count: number;
}

/** One dialogue turn: something a person or Claude actually said. */
export interface TurnNode {
  type: "turn";
  /** Position in the entries array — the `#n` the raw view labels the row with. */
  index: number;
  speaker: Speaker;
  /** Display text: the turn's text with `<system-reminder>` blocks removed. */
  text: string;
  /** Tool calls this turn kicked off, tallied by name. */
  tools: Tally[];
  timestamp?: string;
  sidechain: boolean;
  /** Wall-clock since the previous turn, when both timestamps are known and sane. */
  sincePrevMs?: number;
}

/** A collapsed run of everything that wasn't dialogue. */
export interface HiddenNode {
  type: "hidden";
  /** Index of the first collapsed entry; also the node's stable key. */
  index: number;
  /** The collapsed entries with their original indices, in order. */
  entries: { index: number; entry: TranscriptEntry }[];
  /** Tools invoked inside the run, tallied by name. */
  tools: Tally[];
  /** What the lines were (`tool_result`, `attachment:hook_success`, …). */
  kinds: Tally[];
  /** How many of the collapsed lines carry an error. */
  errorCount: number;
}

export type TimelineNode = TurnNode | HiddenNode;

/**
 * Injected context blocks. They are addressed to the model, can run to thousands of
 * characters, and reading a transcript is not reading them — but they are part of the
 * stored turn, so they stay visible in the raw view.
 */
const SYSTEM_REMINDER = /<system-reminder>[\s\S]*?<\/system-reminder>/g;

/** Tags Claude Code wraps around a synthetic user turn that no one typed. */
const SYNTHETIC_TAG =
  /^<(command-name|command-message|command-args|local-command-stdout|local-command-stderr|user-prompt-submit-hook|bash-input|bash-stdout|bash-stderr)\b/;

/** The preamble Claude Code prepends to locally-generated user turns. */
const CAVEAT = /^Caveat: The messages below were generated by the user while running/;

export function stripSystemReminders(text: string): string {
  return text.replace(SYSTEM_REMINDER, "").trim();
}

/**
 * Is this user turn machinery rather than a prompt?
 *
 * Slash-command echoes, hook output and the local-command caveat all arrive as
 * `role: "user"` with no marker distinguishing them from something typed. Left in,
 * they read as the reader talking to themselves; folded away, the prompts stand out.
 */
export function isSyntheticUserText(text: string): boolean {
  const stripped = stripSystemReminders(text);
  if (!stripped) return true;
  return SYNTHETIC_TAG.test(stripped) || CAVEAT.test(stripped);
}

/**
 * Does this entry belong on the conversation timeline?
 *
 * Only a user prompt or assistant prose. An assistant turn that is purely tool calls
 * says nothing to the reader — the hidden node it folds into already names the tools —
 * and every `kind`-bearing line is by definition not a turn.
 */
export function isDialogue(entry: TranscriptEntry): boolean {
  if (entry.kind) return false;
  const text = stripSystemReminders(entry.text ?? "");
  if (!text) return false;
  if (entry.role === "assistant") return true;
  if (entry.role === "user") return !isSyntheticUserText(entry.text ?? "");
  return false;
}

/** Count occurrences into a tally, highest first, ties by first appearance. */
function tally(names: string[]): Tally[] {
  const counts = new Map<string, number>();
  for (const name of names) counts.set(name, (counts.get(name) ?? 0) + 1);
  return [...counts.entries()]
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);
}

/** What a non-turn line calls itself, for the hidden node's summary. */
function entryKind(entry: TranscriptEntry): string {
  return entry.kind || entry.role || "other";
}

/**
 * Milliseconds between two turns, or undefined when that number would be a lie.
 *
 * Timestamps are optional and transcripts have been seen to go backwards across a
 * resumed session, so a negative gap is dropped rather than rendered as "-3m".
 */
function elapsed(prev: string | undefined, next: string | undefined): number | undefined {
  if (!prev || !next) return undefined;
  const a = Date.parse(prev);
  const b = Date.parse(next);
  if (Number.isNaN(a) || Number.isNaN(b) || b < a) return undefined;
  return b - a;
}

/**
 * Partition transcript entries into dialogue turns and collapsed runs between them.
 *
 * Every input entry lands in exactly one node, in order, so the timeline is a view of
 * the transcript rather than a filtered copy of it.
 */
export function buildTimeline(entries: TranscriptEntry[]): TimelineNode[] {
  const nodes: TimelineNode[] = [];
  let pending: { index: number; entry: TranscriptEntry }[] = [];
  let prevTurnAt: string | undefined;

  const flush = () => {
    if (pending.length === 0) return;
    const run = pending;
    pending = [];
    nodes.push({
      type: "hidden",
      index: run[0]?.index ?? 0,
      entries: run,
      tools: tally(run.flatMap(({ entry }) => (entry.toolUses ?? []).map((t) => t.name))),
      kinds: tally(run.map(({ entry }) => entryKind(entry))),
      errorCount: run.filter(({ entry }) => entry.isError === true).length,
    });
  };

  entries.forEach((entry, index) => {
    if (!isDialogue(entry)) {
      pending.push({ index, entry });
      return;
    }
    flush();
    const turn: TurnNode = {
      type: "turn",
      index,
      speaker: entry.role === "user" ? "user" : "assistant",
      text: stripSystemReminders(entry.text ?? ""),
      tools: tally((entry.toolUses ?? []).map((t) => t.name)),
      sidechain: entry.isSidechain === true,
    };
    if (entry.timestamp) turn.timestamp = entry.timestamp;
    const since = elapsed(prevTurnAt, entry.timestamp);
    if (since !== undefined) turn.sincePrevMs = since;
    prevTurnAt = entry.timestamp ?? prevTurnAt;
    nodes.push(turn);
  });

  flush();
  return nodes;
}

/** `Read ×3` / `Bash`. A count of one is noise. */
export function formatTally(t: Tally): string {
  return t.count > 1 ? `${t.name} ×${t.count}` : t.name;
}

/**
 * The one line a collapsed run shows: what ran, then what else was in there.
 *
 * Tools lead because they are what the reader is scanning for; the kinds are the
 * remainder, capped so a 400-line run doesn't produce a 400-word label.
 */
export function summarizeHidden(node: HiddenNode, max = 3): string {
  const parts: string[] = [];
  const tools = node.tools.slice(0, max).map(formatTally);
  if (node.tools.length > max) tools.push(`+${node.tools.length - max}`);
  if (tools.length) parts.push(tools.join(", "));

  // Once the tools are named, the lines that carried them are implied: after
  // "Read ×3, Bash", adding "tool_result ×4, assistant" says the same thing twice. With
  // no tools to name, though, they're all the run has to describe itself with — a run
  // of results from an earlier page's calls would otherwise summarise as nothing.
  const kinds =
    node.tools.length > 0
      ? node.kinds.filter((k) => k.name !== "tool_result" && k.name !== "assistant")
      : node.kinds;
  const shown = kinds.slice(0, max).map(formatTally);
  if (kinds.length > max) shown.push(`+${kinds.length - max}`);
  if (shown.length) parts.push(shown.join(", "));

  return parts.join(" · ");
}

/** Total lines folded into a run. */
export function hiddenCount(node: HiddenNode): number {
  return node.entries.length;
}

/** How many dialogue turns a timeline holds — the "conversation length" readout. */
export function countTurns(nodes: TimelineNode[]): number {
  return nodes.filter((n) => n.type === "turn").length;
}

/** The node holding a given entry index, or -1. Used to open the run a match is in. */
export function nodeIndexContaining(nodes: TimelineNode[], entryIndex: number): number {
  if (entryIndex < 0) return -1;
  return nodes.findIndex((node) =>
    node.type === "turn"
      ? node.index === entryIndex
      : node.entries.some((e) => e.index === entryIndex),
  );
}
