/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Claude Transcripts
 * OpenAPI spec version: 0.0.0-dev
 */

import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { ErrorType } from "./http";
import { customFetch } from "./http";
export type SessionStatus = (typeof SessionStatus)[keyof typeof SessionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SessionStatus = {
  ended: "ended",
  running: "running",
  incomplete: "incomplete",
} as const;

export interface TokenUsage {
  input: number;
  output: number;
  cacheCreation: number;
  cacheRead: number;
  total: number;
  messages: number;
}

export type SessionSummaryToolCounts = { [key: string]: number };

export interface SessionSummary {
  sessionId: string;
  timestamp: string;
  startTimestamp?: string;
  durationMs?: number;
  activeMs?: number;
  model?: string;
  cwd: string;
  hostname: string;
  eventCount: number;
  promptCount: number;
  errorCount: number;
  toolCounts: SessionSummaryToolCounts;
  endReason: string;
  hasTranscript: boolean;
  transcriptSize?: number;
  status: SessionStatus;
  lastActivity?: string;
  tokenUsage?: TokenUsage;
  source?: string;
}

export interface SessionsResponse {
  sessions: SessionSummary[];
  totalCount: number;
}

export interface ApiError {
  error: string;
}

export type SpeakerRole = (typeof SpeakerRole)[keyof typeof SpeakerRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SpeakerRole = {
  user: "user",
  assistant: "assistant",
  tool_result: "tool_result",
  system: "system",
  other: "other",
} as const;

export interface ToolUseRef {
  name: string;
  id?: string;
}

export interface TranscriptEntry {
  role: SpeakerRole;
  timestamp?: string;
  text?: string;
  /** @nullable */
  toolUses?: ToolUseRef[] | null;
  /** @nullable */
  toolUseId?: string | null;
  isError?: boolean;
  isSidechain?: boolean;
  /** @nullable */
  kind?: string | null;
}

export type TranscriptSource = (typeof TranscriptSource)[keyof typeof TranscriptSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TranscriptSource = {
  chunks: "chunks",
  s3: "s3",
} as const;

export interface TranscriptResponse {
  entries: TranscriptEntry[];
  totalCount: number;
  hasMore: boolean;
  source: TranscriptSource;
  byteCoverage: number;
}

export interface SpeakerTurn {
  role: SpeakerRole;
  timestamp: string;
  text: string;
  /** @nullable */
  toolUses?: ToolUseRef[] | null;
  /** @nullable */
  toolUseId?: string | null;
  isError?: boolean;
}

/**
 * @nullable
 */
export type SessionTurnsResponseRoleAllOf = unknown | null;

export type SessionTurnsResponseRole = SpeakerRole & SessionTurnsResponseRoleAllOf;

export interface SessionTurnsResponse {
  turns: SpeakerTurn[];
  totalCount: number;
  hasMore: boolean;
  role: SessionTurnsResponseRole;
}

export interface CrossSessionTurn {
  sessionId: string;
  cwd: string;
  role: SpeakerRole;
  timestamp: string;
  text: string;
}

/**
 * @nullable
 */
export type CrossSessionTurnsResponseRoleAllOf = unknown | null;

export type CrossSessionTurnsResponseRole = SpeakerRole & CrossSessionTurnsResponseRoleAllOf;

export interface CrossSessionTurnsResponse {
  turns: CrossSessionTurn[];
  hasMore: boolean;
  role: CrossSessionTurnsResponseRole;
}

export type SessionResetResultDeleted = {
  summary: number;
  events: number;
  chunks: number;
};

export interface SessionResetResult {
  ok: boolean;
  id: string;
  deleted: SessionResetResultDeleted;
}

export interface SearchHit {
  sessionId: string;
  timestamp?: string;
  cwd?: string;
  model?: string;
  hostname?: string;
  endReason?: string;
  source?: string;
  tools?: string[];
}

export interface TurnHit {
  sessionId: string;
  role: string;
  snippet: string;
  timestamp?: string;
  cwd?: string;
}

export interface SearchResponse {
  hits: SearchHit[];
  turns: TurnHit[];
  query: string;
  enabled: boolean;
}

export interface IndexCounts {
  scanned: number;
  indexed: number;
}

export interface ReindexResult {
  enabled: boolean;
  sessions: IndexCounts;
  turns: IndexCounts;
  failures: string[];
}

export interface MigrationStep {
  id: number;
  name: string;
}

export interface AppliedMigration {
  id: number;
  name: string;
  at: string;
}

export interface MigrationStatus {
  currentVersion: number;
  latestVersion: number;
  pending: MigrationStep[];
  history: AppliedMigration[];
}

export type MigrationDirection = (typeof MigrationDirection)[keyof typeof MigrationDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MigrationDirection = {
  up: "up",
  down: "down",
} as const;

export interface MigrationRunResult {
  direction: MigrationDirection;
  fromVersion: number;
  toVersion: number;
  applied: MigrationStep[];
  dryRun: boolean;
  log: string[];
}

export type ListSessionsParams = {
  /**
   * @minimum 0
   * @nullable
   */
  limit?: number | null;
  /**
   * @minimum 0
   * @nullable
   */
  skip?: number | null;
};

export type GetSessionTranscriptParams = {
  /**
   * @minimum 0
   * @nullable
   */
  limit?: number | null;
  /**
   * @minimum 0
   * @nullable
   */
  offset?: number | null;
};

export type GetSessionTurnsParams = {
  role?: SpeakerRole;
  /**
   * @minimum 0
   * @nullable
   */
  limit?: number | null;
  /**
   * @minimum 0
   * @nullable
   */
  offset?: number | null;
};

export type GetTurnsParams = {
  role?: SpeakerRole;
  from?: string;
  to?: string;
  /**
   * @minimum 0
   * @nullable
   */
  limit?: number | null;
  /**
   * @minimum 0
   * @nullable
   */
  skip?: number | null;
};

export type IngestSummaryBodyType =
  (typeof IngestSummaryBodyType)[keyof typeof IngestSummaryBodyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IngestSummaryBodyType = {
  summary: "summary",
} as const;

export type IngestSummaryBodyEvent =
  (typeof IngestSummaryBodyEvent)[keyof typeof IngestSummaryBodyEvent];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IngestSummaryBodyEvent = {
  SessionEnd: "SessionEnd",
} as const;

export type IngestSummaryBodyToolCounts = { [key: string]: number };

export type IngestSummaryBodyTokenUsage = {
  input: number;
  output: number;
  cacheCreation: number;
  cacheRead: number;
  total: number;
  messages: number;
};

export type IngestSummaryBody = {
  _id: string;
  type: IngestSummaryBodyType;
  event: IngestSummaryBodyEvent;
  session_id: string;
  timestamp: string;
  hostname: string;
  cwd: string;
  model?: string;
  end_reason: string;
  event_count: number;
  prompt_count: number;
  error_count: number;
  tool_counts: IngestSummaryBodyToolCounts;
  transcript_bytes: number;
  token_usage: IngestSummaryBodyTokenUsage;
  source?: string;
  backfilled_at?: string;
  actor?: string;
};

export type IngestSummary200 = {
  ok: boolean;
  id?: string;
  updated?: boolean;
  inserted?: number;
  bytes?: number;
};

export type IngestSummary400 = {
  error: string;
};

export type IngestSummary500 = {
  error: string;
};

export type IngestEventsBodyDocsItemType =
  (typeof IngestEventsBodyDocsItemType)[keyof typeof IngestEventsBodyDocsItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IngestEventsBodyDocsItemType = {
  event: "event",
} as const;

export type IngestEventsBodyDocsItem = {
  type: IngestEventsBodyDocsItemType;
  event: string;
  session_id: string;
  timestamp: string;
  hostname: string;
  cwd: string;
};

export type IngestEventsBody = {
  docs: IngestEventsBodyDocsItem[];
};

export type IngestEvents200 = {
  ok: boolean;
  id?: string;
  updated?: boolean;
  inserted?: number;
  bytes?: number;
};

export type IngestEvents400 = {
  error: string;
};

export type IngestEvents500 = {
  error: string;
};

export type IngestChunksBodyDocsItemType =
  (typeof IngestChunksBodyDocsItemType)[keyof typeof IngestChunksBodyDocsItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IngestChunksBodyDocsItemType = {
  chunk: "chunk",
} as const;

export type IngestChunksBodyDocsItemEntriesItemRole =
  (typeof IngestChunksBodyDocsItemEntriesItemRole)[keyof typeof IngestChunksBodyDocsItemEntriesItemRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IngestChunksBodyDocsItemEntriesItemRole = {
  user: "user",
  assistant: "assistant",
  tool_result: "tool_result",
  system: "system",
  other: "other",
} as const;

export type IngestChunksBodyDocsItemEntriesItemToolUsesItem = {
  name: string;
  id?: string;
};

export type IngestChunksBodyDocsItemEntriesItem = {
  role: IngestChunksBodyDocsItemEntriesItemRole;
  timestamp?: string;
  text?: string;
  toolUses?: IngestChunksBodyDocsItemEntriesItemToolUsesItem[];
  toolUseId?: string;
  isError?: boolean;
  isSidechain?: boolean;
};

export type IngestChunksBodyDocsItem = {
  _id: string;
  type: IngestChunksBodyDocsItemType;
  session_id: string;
  byte_start: number;
  byte_end: number;
  entry_count: number;
  timestamp: string;
  hostname: string;
  cwd: string;
  schema_version: number;
  entries?: IngestChunksBodyDocsItemEntriesItem[];
};

export type IngestChunksBody = {
  docs: IngestChunksBodyDocsItem[];
};

export type IngestChunks200 = {
  ok: boolean;
  id?: string;
  updated?: boolean;
  inserted?: number;
  bytes?: number;
};

export type IngestChunks400 = {
  error: string;
};

export type IngestChunks500 = {
  error: string;
};

export type IngestTranscript200 = {
  ok: boolean;
  id?: string;
  updated?: boolean;
  inserted?: number;
  bytes?: number;
};

export type IngestTranscript400 = {
  error: string;
};

export type IngestTranscript500 = {
  error: string;
};

export type ResetSession400 = {
  error: string;
};

export type ResetSession500 = {
  error: string;
};

export type SearchParams = {
  q?: string;
  /**
   * @minimum 0
   * @nullable
   */
  limit?: number | null;
};

export type MigrateUpBody = {
  to?: number;
  dryRun?: boolean;
};

export type MigrateDownBody = {
  steps?: number;
  dryRun?: boolean;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getListSessionsUrl = (params?: ListSessionsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sessions?${stringifiedParams}` : `/api/sessions`;
};

export const listSessions = async (
  params?: ListSessionsParams,
  options?: RequestInit,
): Promise<SessionsResponse> => {
  return customFetch<SessionsResponse>(getListSessionsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListSessionsQueryKey = (params?: ListSessionsParams) => {
  return [`/api/sessions`, ...(params ? [params] : [])] as const;
};

export const getListSessionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listSessions>>,
  TError = ErrorType<ApiError>,
>(
  params?: ListSessionsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListSessionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listSessions>>> = ({ signal }) =>
    listSessions(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listSessions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listSessions>>>;
export type ListSessionsQueryError = ErrorType<ApiError>;

export function useListSessions<
  TData = Awaited<ReturnType<typeof listSessions>>,
  TError = ErrorType<ApiError>,
>(
  params?: ListSessionsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListSessionsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetSessionUrl = (id: string) => {
  return `/api/sessions/${id}`;
};

export const getSession = async (id: string, options?: RequestInit): Promise<SessionSummary> => {
  return customFetch<SessionSummary>(getGetSessionUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetSessionQueryKey = (id?: string) => {
  return [`/api/sessions/${id}`] as const;
};

export const getGetSessionQueryOptions = <
  TData = Awaited<ReturnType<typeof getSession>>,
  TError = ErrorType<ApiError>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSessionQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSession>>> = ({ signal }) =>
    getSession(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSession>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getSession>>>;
export type GetSessionQueryError = ErrorType<ApiError>;

export function useGetSession<
  TData = Awaited<ReturnType<typeof getSession>>,
  TError = ErrorType<ApiError>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSessionQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetSessionTranscriptUrl = (id: string, params?: GetSessionTranscriptParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/sessions/${id}/transcript?${stringifiedParams}`
    : `/api/sessions/${id}/transcript`;
};

export const getSessionTranscript = async (
  id: string,
  params?: GetSessionTranscriptParams,
  options?: RequestInit,
): Promise<TranscriptResponse> => {
  return customFetch<TranscriptResponse>(getGetSessionTranscriptUrl(id, params), {
    ...options,
    method: "GET",
  });
};

export const getGetSessionTranscriptQueryKey = (
  id?: string,
  params?: GetSessionTranscriptParams,
) => {
  return [`/api/sessions/${id}/transcript`, ...(params ? [params] : [])] as const;
};

export const getGetSessionTranscriptQueryOptions = <
  TData = Awaited<ReturnType<typeof getSessionTranscript>>,
  TError = ErrorType<ApiError>,
>(
  id: string,
  params?: GetSessionTranscriptParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getSessionTranscript>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSessionTranscriptQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSessionTranscript>>> = ({ signal }) =>
    getSessionTranscript(id, params, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSessionTranscript>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSessionTranscriptQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSessionTranscript>>
>;
export type GetSessionTranscriptQueryError = ErrorType<ApiError>;

export function useGetSessionTranscript<
  TData = Awaited<ReturnType<typeof getSessionTranscript>>,
  TError = ErrorType<ApiError>,
>(
  id: string,
  params?: GetSessionTranscriptParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getSessionTranscript>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSessionTranscriptQueryOptions(id, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetSessionTurnsUrl = (id: string, params?: GetSessionTurnsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/sessions/${id}/turns?${stringifiedParams}`
    : `/api/sessions/${id}/turns`;
};

export const getSessionTurns = async (
  id: string,
  params?: GetSessionTurnsParams,
  options?: RequestInit,
): Promise<SessionTurnsResponse> => {
  return customFetch<SessionTurnsResponse>(getGetSessionTurnsUrl(id, params), {
    ...options,
    method: "GET",
  });
};

export const getGetSessionTurnsQueryKey = (id?: string, params?: GetSessionTurnsParams) => {
  return [`/api/sessions/${id}/turns`, ...(params ? [params] : [])] as const;
};

export const getGetSessionTurnsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSessionTurns>>,
  TError = ErrorType<ApiError>,
>(
  id: string,
  params?: GetSessionTurnsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getSessionTurns>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSessionTurnsQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSessionTurns>>> = ({ signal }) =>
    getSessionTurns(id, params, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSessionTurns>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSessionTurnsQueryResult = NonNullable<Awaited<ReturnType<typeof getSessionTurns>>>;
export type GetSessionTurnsQueryError = ErrorType<ApiError>;

export function useGetSessionTurns<
  TData = Awaited<ReturnType<typeof getSessionTurns>>,
  TError = ErrorType<ApiError>,
>(
  id: string,
  params?: GetSessionTurnsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getSessionTurns>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSessionTurnsQueryOptions(id, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetTurnsUrl = (params?: GetTurnsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/turns?${stringifiedParams}` : `/api/turns`;
};

export const getTurns = async (
  params?: GetTurnsParams,
  options?: RequestInit,
): Promise<CrossSessionTurnsResponse> => {
  return customFetch<CrossSessionTurnsResponse>(getGetTurnsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetTurnsQueryKey = (params?: GetTurnsParams) => {
  return [`/api/turns`, ...(params ? [params] : [])] as const;
};

export const getGetTurnsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTurns>>,
  TError = ErrorType<ApiError>,
>(
  params?: GetTurnsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getTurns>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTurnsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTurns>>> = ({ signal }) =>
    getTurns(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTurns>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTurnsQueryResult = NonNullable<Awaited<ReturnType<typeof getTurns>>>;
export type GetTurnsQueryError = ErrorType<ApiError>;

export function useGetTurns<
  TData = Awaited<ReturnType<typeof getTurns>>,
  TError = ErrorType<ApiError>,
>(
  params?: GetTurnsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getTurns>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTurnsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getIngestSummaryUrl = () => {
  return `/api/ingest/summary`;
};

export const ingestSummary = async (
  ingestSummaryBody: IngestSummaryBody,
  options?: RequestInit,
): Promise<IngestSummary200> => {
  return customFetch<IngestSummary200>(getIngestSummaryUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(ingestSummaryBody),
  });
};

export const getIngestSummaryMutationOptions = <
  TError = ErrorType<IngestSummary400 | IngestSummary500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ingestSummary>>,
    TError,
    { data: IngestSummaryBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ingestSummary>>,
  TError,
  { data: IngestSummaryBody },
  TContext
> => {
  const mutationKey = ["ingestSummary"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ingestSummary>>,
    { data: IngestSummaryBody }
  > = (props) => {
    const { data } = props ?? {};

    return ingestSummary(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type IngestSummaryMutationResult = NonNullable<Awaited<ReturnType<typeof ingestSummary>>>;
export type IngestSummaryMutationBody = IngestSummaryBody;
export type IngestSummaryMutationError = ErrorType<IngestSummary400 | IngestSummary500>;

export const useIngestSummary = <
  TError = ErrorType<IngestSummary400 | IngestSummary500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ingestSummary>>,
    TError,
    { data: IngestSummaryBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof ingestSummary>>,
  TError,
  { data: IngestSummaryBody },
  TContext
> => {
  const mutationOptions = getIngestSummaryMutationOptions(options);

  return useMutation(mutationOptions);
};

export const getIngestEventsUrl = () => {
  return `/api/ingest/events`;
};

export const ingestEvents = async (
  ingestEventsBody: IngestEventsBody,
  options?: RequestInit,
): Promise<IngestEvents200> => {
  return customFetch<IngestEvents200>(getIngestEventsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(ingestEventsBody),
  });
};

export const getIngestEventsMutationOptions = <
  TError = ErrorType<IngestEvents400 | IngestEvents500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ingestEvents>>,
    TError,
    { data: IngestEventsBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ingestEvents>>,
  TError,
  { data: IngestEventsBody },
  TContext
> => {
  const mutationKey = ["ingestEvents"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ingestEvents>>,
    { data: IngestEventsBody }
  > = (props) => {
    const { data } = props ?? {};

    return ingestEvents(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type IngestEventsMutationResult = NonNullable<Awaited<ReturnType<typeof ingestEvents>>>;
export type IngestEventsMutationBody = IngestEventsBody;
export type IngestEventsMutationError = ErrorType<IngestEvents400 | IngestEvents500>;

export const useIngestEvents = <
  TError = ErrorType<IngestEvents400 | IngestEvents500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ingestEvents>>,
    TError,
    { data: IngestEventsBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof ingestEvents>>,
  TError,
  { data: IngestEventsBody },
  TContext
> => {
  const mutationOptions = getIngestEventsMutationOptions(options);

  return useMutation(mutationOptions);
};

export const getIngestChunksUrl = () => {
  return `/api/ingest/chunks`;
};

export const ingestChunks = async (
  ingestChunksBody: IngestChunksBody,
  options?: RequestInit,
): Promise<IngestChunks200> => {
  return customFetch<IngestChunks200>(getIngestChunksUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(ingestChunksBody),
  });
};

export const getIngestChunksMutationOptions = <
  TError = ErrorType<IngestChunks400 | IngestChunks500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ingestChunks>>,
    TError,
    { data: IngestChunksBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ingestChunks>>,
  TError,
  { data: IngestChunksBody },
  TContext
> => {
  const mutationKey = ["ingestChunks"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ingestChunks>>,
    { data: IngestChunksBody }
  > = (props) => {
    const { data } = props ?? {};

    return ingestChunks(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type IngestChunksMutationResult = NonNullable<Awaited<ReturnType<typeof ingestChunks>>>;
export type IngestChunksMutationBody = IngestChunksBody;
export type IngestChunksMutationError = ErrorType<IngestChunks400 | IngestChunks500>;

export const useIngestChunks = <
  TError = ErrorType<IngestChunks400 | IngestChunks500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ingestChunks>>,
    TError,
    { data: IngestChunksBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof ingestChunks>>,
  TError,
  { data: IngestChunksBody },
  TContext
> => {
  const mutationOptions = getIngestChunksMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Store a session transcript (raw JSONL body, application/x-ndjson) in S3
 */
export const getIngestTranscriptUrl = (id: string) => {
  return `/api/ingest/${id}/transcript`;
};

export const ingestTranscript = async (
  id: string,
  options?: RequestInit,
): Promise<IngestTranscript200> => {
  return customFetch<IngestTranscript200>(getIngestTranscriptUrl(id), {
    ...options,
    method: "PUT",
  });
};

export const getIngestTranscriptMutationOptions = <
  TError = ErrorType<IngestTranscript400 | IngestTranscript500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ingestTranscript>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ingestTranscript>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["ingestTranscript"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ingestTranscript>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return ingestTranscript(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type IngestTranscriptMutationResult = NonNullable<
  Awaited<ReturnType<typeof ingestTranscript>>
>;

export type IngestTranscriptMutationError = ErrorType<IngestTranscript400 | IngestTranscript500>;

/**
 * @summary Store a session transcript (raw JSONL body, application/x-ndjson) in S3
 */
export const useIngestTranscript = <
  TError = ErrorType<IngestTranscript400 | IngestTranscript500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ingestTranscript>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof ingestTranscript>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getIngestTranscriptMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Delete a session's summary/event/chunk docs so it can be re-ingested
 */
export const getResetSessionUrl = (id: string) => {
  return `/api/ingest/${id}`;
};

export const resetSession = async (
  id: string,
  options?: RequestInit,
): Promise<SessionResetResult> => {
  return customFetch<SessionResetResult>(getResetSessionUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getResetSessionMutationOptions = <
  TError = ErrorType<ResetSession400 | ResetSession500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetSession>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof resetSession>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["resetSession"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetSession>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return resetSession(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ResetSessionMutationResult = NonNullable<Awaited<ReturnType<typeof resetSession>>>;

export type ResetSessionMutationError = ErrorType<ResetSession400 | ResetSession500>;

/**
 * @summary Delete a session's summary/event/chunk docs so it can be re-ingested
 */
export const useResetSession = <
  TError = ErrorType<ResetSession400 | ResetSession500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetSession>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof resetSession>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getResetSessionMutationOptions(options);

  return useMutation(mutationOptions);
};

export const getSearchUrl = (params?: SearchParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/search?${stringifiedParams}` : `/api/search`;
};

export const search = async (
  params?: SearchParams,
  options?: RequestInit,
): Promise<SearchResponse> => {
  return customFetch<SearchResponse>(getSearchUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getSearchQueryKey = (params?: SearchParams) => {
  return [`/api/search`, ...(params ? [params] : [])] as const;
};

export const getSearchQueryOptions = <
  TData = Awaited<ReturnType<typeof search>>,
  TError = ErrorType<ApiError>,
>(
  params?: SearchParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof search>>> = ({ signal }) =>
    search(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof search>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type SearchQueryResult = NonNullable<Awaited<ReturnType<typeof search>>>;
export type SearchQueryError = ErrorType<ApiError>;

export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = ErrorType<ApiError>>(
  params?: SearchParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSearchQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSearchReindexUrl = () => {
  return `/api/search/reindex`;
};

export const searchReindex = async (options?: RequestInit): Promise<ReindexResult> => {
  return customFetch<ReindexResult>(getSearchReindexUrl(), {
    ...options,
    method: "POST",
  });
};

export const getSearchReindexMutationOptions = <
  TError = ErrorType<ApiError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof searchReindex>>, TError, void, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof searchReindex>>, TError, void, TContext> => {
  const mutationKey = ["searchReindex"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof searchReindex>>, void> = () => {
    return searchReindex(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SearchReindexMutationResult = NonNullable<Awaited<ReturnType<typeof searchReindex>>>;

export type SearchReindexMutationError = ErrorType<ApiError>;

export const useSearchReindex = <TError = ErrorType<ApiError>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof searchReindex>>, TError, void, TContext>;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<Awaited<ReturnType<typeof searchReindex>>, TError, void, TContext> => {
  const mutationOptions = getSearchReindexMutationOptions(options);

  return useMutation(mutationOptions);
};

export const getMigrateStatusUrl = () => {
  return `/api/migrate/status`;
};

export const migrateStatus = async (options?: RequestInit): Promise<MigrationStatus> => {
  return customFetch<MigrationStatus>(getMigrateStatusUrl(), {
    ...options,
    method: "GET",
  });
};

export const getMigrateStatusQueryKey = () => {
  return [`/api/migrate/status`] as const;
};

export const getMigrateStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof migrateStatus>>,
  TError = ErrorType<ApiError>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof migrateStatus>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMigrateStatusQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof migrateStatus>>> = ({ signal }) =>
    migrateStatus({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof migrateStatus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type MigrateStatusQueryResult = NonNullable<Awaited<ReturnType<typeof migrateStatus>>>;
export type MigrateStatusQueryError = ErrorType<ApiError>;

export function useMigrateStatus<
  TData = Awaited<ReturnType<typeof migrateStatus>>,
  TError = ErrorType<ApiError>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof migrateStatus>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getMigrateStatusQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getMigrateUpUrl = () => {
  return `/api/migrate/up`;
};

export const migrateUp = async (
  migrateUpBody?: MigrateUpBody,
  options?: RequestInit,
): Promise<MigrationRunResult> => {
  return customFetch<MigrationRunResult>(getMigrateUpUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(migrateUpBody),
  });
};

export const getMigrateUpMutationOptions = <
  TError = ErrorType<ApiError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof migrateUp>>,
    TError,
    { data: MigrateUpBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof migrateUp>>,
  TError,
  { data: MigrateUpBody },
  TContext
> => {
  const mutationKey = ["migrateUp"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof migrateUp>>,
    { data: MigrateUpBody }
  > = (props) => {
    const { data } = props ?? {};

    return migrateUp(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MigrateUpMutationResult = NonNullable<Awaited<ReturnType<typeof migrateUp>>>;
export type MigrateUpMutationBody = MigrateUpBody;
export type MigrateUpMutationError = ErrorType<ApiError>;

export const useMigrateUp = <TError = ErrorType<ApiError>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof migrateUp>>,
    TError,
    { data: MigrateUpBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof migrateUp>>,
  TError,
  { data: MigrateUpBody },
  TContext
> => {
  const mutationOptions = getMigrateUpMutationOptions(options);

  return useMutation(mutationOptions);
};

export const getMigrateDownUrl = () => {
  return `/api/migrate/down`;
};

export const migrateDown = async (
  migrateDownBody?: MigrateDownBody,
  options?: RequestInit,
): Promise<MigrationRunResult> => {
  return customFetch<MigrationRunResult>(getMigrateDownUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(migrateDownBody),
  });
};

export const getMigrateDownMutationOptions = <
  TError = ErrorType<ApiError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof migrateDown>>,
    TError,
    { data: MigrateDownBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof migrateDown>>,
  TError,
  { data: MigrateDownBody },
  TContext
> => {
  const mutationKey = ["migrateDown"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof migrateDown>>,
    { data: MigrateDownBody }
  > = (props) => {
    const { data } = props ?? {};

    return migrateDown(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MigrateDownMutationResult = NonNullable<Awaited<ReturnType<typeof migrateDown>>>;
export type MigrateDownMutationBody = MigrateDownBody;
export type MigrateDownMutationError = ErrorType<ApiError>;

export const useMigrateDown = <TError = ErrorType<ApiError>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof migrateDown>>,
    TError,
    { data: MigrateDownBody },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof migrateDown>>,
  TError,
  { data: MigrateDownBody },
  TContext
> => {
  const mutationOptions = getMigrateDownMutationOptions(options);

  return useMutation(mutationOptions);
};
